#!/bin/sh

### This file is managed by Puppet, don't edit it. ###

# Grub just in /dev/sdb because no RAID soft.
for device in /dev/sdb
do
    for symlink in /dev/disk/by-id/*
    do
        if [ "$device" = "$(readlink -f $symlink)" ]
        then
            device_id="$symlink"
        fi
    done

    if [ -z "$device_grub_target" ]
    then
        device_grub_target="$device_id"
    else
        device_grub_target="$device_grub_target, $device_id"
    fi

done

printf "grub-pc grub-pc/install_devices multiselect %s\n" "$device_grub_target" >/target/tmp/debconf.grub

mount --bind /dev/pts /target/dev/pts
mount --bind /proc    /target/proc
mount --bind /sys     /target/sys

# I don't know why but if I use `chroot /target ...` instead of
# `in-target`, it doesn't work.
in-target /bin/bash -c 'debconf-set-selections </tmp/debconf.grub >>/tmp/log 2>&1'
in-target /bin/bash -c 'DEBIAN_FRONTEND=noninteractive apt-get install --yes grub-pc >>/tmp/log 2>&1'

umount /target/dev/pts
umount /target/proc
umount /target/sys
exit 0


