#!/bin/sh

### This file is managed by Puppet, don't edit it. ###

exec >/tmp/partition.log 2>&1
set -x

parted='parted --script --align=opt'

$parted /dev/sdb mktable gpt

part_num=1

# The unused UEFI partition if one day we decide
# to enable the Bios-UEFI.
# I don't know why but, _during the Trusty installation_
# if I set a == 1 (MiB) the partition not begins at 1 MiB
# but at 0.25MiB (for me it's a bug in the Trusty debian-installer).
# If I use 2048s instead, it works (???).
a=2048s
b=$((250 + 1)) # Size == 250MiB
$parted /dev/sdb unit MiB mkpart uefiunused $a $b
part_num=$((part_num + 1))


# The biosgrub partition.
a=$b
b=$((1 + a)) # Size == 1MiB
$parted /dev/sdb unit MiB mkpart biosgrub $a $b
$parted /dev/sdb set $part_num bios_grub on
part_num=$((part_num + 1))


# The root partition.
a=$b
b=$((30 * 1024 + a)) # Size == 30GiB
$parted /dev/sdb unit MiB mkpart system $a $b
part_num=$((part_num + 1))


# The swap.
a=$b
b=$((8 * 1024 + a)) # Size == 8GiB
$parted /dev/sdb unit MiB mkpart swap linux-swap $a $b
part_num=$((part_num + 1))


# The remaining of the disk is a /backups partition.
a=$b
b='-1cyl' # The last cylinder
$parted /dev/sdb -- unit MiB mkpart backups $a $b
part_num=$((part_num + 1))

### Creation of the file systems. ###

mkfs.ext4 -F -E lazy_itable_init=0 -L system /dev/sdb3
mkswap -L swap /dev/sdb4
mkfs.xfs -f -L backups /dev/sdb5


