#!/bin/bash

### This file is managed by puppet, don't exist
#
# It's just a basic script to launch a puppet run
# via a cron task.
#

export LC_ALL=C
export PATH='/opt/puppetlabs/bin:/usr/sbin:/usr/bin:/sbin:/bin'

exec >/dev/null 2>&1
timeout --signal TERM --kill-after 120s 360s puppet agent --test


