#!/usr/bin/ruby
# Copyright: 2014 Francois Lafont <francois.lafont@ac-versailles.fr>

require 'yaml'

env_dir = '/usr/local/src/puppet'
fqdn = ARGV[0]

# Ouput of the ENC which must be completed.
output = '{
  "parameters":
  {
    "environment": "###environment###",
    "admin_email": "admin@crdp.ac-versailles.fr",
    ###parameters###
  }
}
'

# Search for the yaml file in hieradata.
files_array = Dir.glob("#{env_dir}/*/hieradata/fqdn/#{fqdn}.yaml")
if files_array.length != 1
  puts "Sorry, in hieradata, the file `#{fqdn}.yaml' " \
       "is not present or is duplicated."
  exit(1)
end

# There is just one fqdn.yaml file in hieradata.
yaml_file = files_array[0]

# Get the environment variable.
regex_end = "/hieradata/fqdn/#{fqdn}.yaml"
environment = yaml_file.sub(/^#{env_dir}\//, '').sub(/#{regex_end}$/, '')

# Search for keys which match /^enc_/ in the yaml file to
# define the global paramters.
hash = YAML.load_file(yaml_file)
parameters = ''

hash.each do |key, value|

  if key =~ /^enc_/

    key = key.sub(/^enc_/, '')

    # Handle when the value is a string.
    if value.is_a?(String) or value.is_a?(Numeric)
      if value.is_a?(Numeric) then value = value.to_s() end
      value = value.gsub('"', '\\"') # Escape " in value.
      parameters += "\"#{key}\": \"#{value}\",\n    "
    end

    # Handle when the value is a array.
    if value.is_a?(Array)
      c = 0
      for e in value
        if e.is_a?(String) or e.is_a?(Numeric)
          if e.is_a?(Numeric) then e = e.to_s() end
          e = e.gsub('"', '\\"') # Escape " in e.
          parameters += "\"#{key}_#{c}\": \"#{e}\",\n    "
          c += 1
        end
      end
    end

  end

end
parameters = parameters.strip()

output = output.sub('###environment###', environment)
output = output.sub('###parameters###', parameters)
puts output
exit(0)

