#!/usr/bin/ruby
# Copyright: 2014 Francois Lafont <francois.lafont@ac-versailles.fr>

require 'yaml'

env_dir = '/usr/local/src/puppet'
fqdn = ARGV[0]

# Ouput of the ENC which must be completed.
output = '{
  parameters:
  {
    "environment": "###environment###",
    "admin_email": "admin@crdp.ac-versailles.fr",
    ###parameters###
  }
}
'

# Search for the yaml file in hieradata.
files_array = Dir.glob("#{env_dir}/*/hieradata/fqdn/#{fqdn}.yaml")
if files_array.length != 1
    puts "Sorry, in hieradata, the file `#{fqdn}.yaml' " \
         "is not present or is duplicated."
    exit(1)
end

# There is just one fqdn.yaml file in hieradata.
yaml_file = files_array[0]

# Get the environment variable.
regex_end = "/hieradata/fqdn/#{fqdn}.yaml"
environment = yaml_file.sub(/^#{env_dir}\//, '').sub(/#{regex_end}$/, '')

# Search for keys which match /^enc_/ in the yaml file to
# define the global paramters.
hash = YAML.load_file(yaml_file)
parameters = ''

hash.each do |key, value|
    if key =~ /^enc_/
        if value.is_a?(String)
            key = key.sub(/^enc_/, '')
            # Escape " in value.
            value = value.gsub('"', '\\"')
            parameters += "\"#{key}\": \"#{value}\",\n    "
        end
    end
end
parameters = parameters.strip()

output = output.sub('###parameters###', parameters)
output = output.sub('###environment###', environment)
puts output
exit(0)

