#!/bin/sh
### This file is managed by Puppet, don't edit it. ###

export LC_ALL='C'
export PATH='/usr/sbin:/usr/bin:/sbin:/bin'

# Deconfigure all interfaces except lo.
# Note: with Ubuntu 14.04, the init script doesn't work.
ifdown --all
sleep 1

if [ -f '/etc/network/interfaces.puppet' ]
then
    cat '/etc/network/interfaces.puppet' > '/etc/network/interfaces'
fi

# Refresh the names of interfaces.
udevadm control --reload-rules
sleep 1
udevadm trigger --subsystem-match='net' --action='add'
sleep 1

# Configure all interfaces marked 'auto'
ifup --all
sleep 1


