---
shinken_tag: 'shinken_lab'

snmp:

  # Definition of views.
  views:
    monitoring:
      - '.1.3.6.1.2.1'
      - '.1.3.6.1.4.1'

  # The SNMPv3 configuration (authentification and view).
  secname: '__pwd__{"salt" => ["$datacenter", "snmp-secname"], "nice" => true, "max_length" => 12}'
  authpass: '__pwd__{"salt" => ["$datacenter", "snmp-authpass"]}'
  authproto: 'sha'
  privpass: '__pwd__{"salt" => ["$datacenter", "snmp-privpass"], "nice" => true, "case" => "upper"}'
  privproto: 'aes'
  secview: 'monitoring'

  # The community password for SNMPv2c.
  community: 'communitypass'

  # Addresses allowed to do SNMPv2c requests and the corresponding view.
  sources:
    'localhost': 'monitoring'
    '192.168.0.4': 'monitoring'
    '192.168.0.5': 'monitoring'


