#!/bin/sh

ROOT_DIR=$(cd $(dirname "$0"); pwd)
PUPPET_DIR='/puppet/production'

# Hiera.
cat "$ROOT_DIR/default.yaml" > "$PUPPET_DIR/hieradata/default.yaml"
cat "$ROOT_DIR/shinken.athome.priv.yaml" > "$PUPPET_DIR/hieradata/fqdn/shinken.athome.priv.yaml"
cat "$ROOT_DIR/node.athome.priv.yaml" > "$PUPPET_DIR/hieradata/fqdn/node.athome.priv.yaml"
echo "---" > "$PUPPET_DIR/hieradata/datacenter/lss.yaml"
echo "---" > "$PUPPET_DIR/hieradata/datacenter/vty.yaml"

# Add the exim4 class to send mails.
rm -rf "$PUPPET_DIR/modules/exim4"
cp -ar "$ROOT_DIR/exim4" "$PUPPET_DIR/modules/"

# Change interval_length parameter.
sed -i 's/^interval_length=.*$/interval_length=2/' "$PUPPET_DIR/modules/shinken/templates/server/nagios.cfg.erb"


