HTTP/1.0 503 Service Unavailable
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Erreur 503</title>
        <style>
        @import url('https://fonts.googleapis.com/css?family=Luckiest+Guy');
          h1, h2 {
            font-family: 'Luckiest Guy';
            color: #718DA3;
          }
          h1{
            font-size: 9vw;
            margin:0.7em auto 0 0.5em;
          }
          h2 {
            font-size: 3vw;
            margin:0 auto 0.2em 1.5em;
          }
        </style>
    </head>

    <body>
      <h1>Elea ?</h1>
      <h2>Inconnue à cette adresse...</h2>
    </body>
</html>


