# -*- mode: ruby -*-

HOME            = ENV['HOME']
VAGRANT_COMMAND = ARGV[0]
RAM             = if ENV['V_RAM'].nil? then 512 else ENV['V_RAM'] end

privkey_path = "#{HOME}/.ssh/id_rsa"
pubkey_path  = "#{HOME}/.ssh/id_rsa.pub"
pubkey       = File.open(pubkey_path, 'r').read
script       = File.open('../share/provision.sh', 'r').read.gsub('__PUBKEY__', pubkey)

Vagrant.configure(2) do |config|

  config.vm.provision 'shell', inline: script

  if VAGRANT_COMMAND == "ssh"
    config.ssh.username         = 'root'
    config.ssh.private_key_path = privkey_path
    config.ssh.forward_agent    = true
  end

  VMs = {
    'trustyclean' => {
      'iface1' => { 'mac' => '080027000011', 'ip' => 'N/A' },
      'box'    => 'flaf/trusty',
    },
    'jessieclean' => {
      'iface1' => { 'mac' => '080027000021', 'ip' => 'N/A' },
      'box'    => 'flaf/jessie',
    },
  }

  VMs.each do |hostname, settings|

    config.vm.define hostname, autostart: false do |h|

      h.vm.box      = settings['box']
      h.vm.hostname = hostname

      h.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--memory", RAM]
        v.customize ["modifyvm", :id, "--name", "v-#{hostname}"]
        v.customize ["modifyvm", :id, "--cpus", 1]
      end

    end

  end # End of VMs.each...

end


