#!/bin/sh

URL='https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc'
CEPH_RELEASE="firefly"

# Add the release key.
if ! (apt-key list | grep -qi 'Ceph Release Key')
then
    wget -q -O- "$URL" | apt-key add -
fi

# Add the Ceph repository.
echo "deb http://ceph.com/debian-$CEPH_RELEASE/ $(lsb_release -sc) main" > "/etc/apt/sources.list.d/ceph.list"

# Configure /etc/hosts. The hostname must be
# resolved with a non loopback IP address.
host_name=$(hostname)
fqdn=$(hostname -f)
ipaddress=$(facter ipaddress)
sed -r -i "s/^.*$fqdn.*$/$ipaddress\t$fqdn\t$host_name/" "/etc/hosts"


