#!/bin/sh


# Characters just in [a-z0-9] for the cluster name.
cluster="$1"
mon_id="$2"
other_mons="$3" # ex: "ceph-node2:m2:172.31.9.2 ceph-node3:m3:172.31.9.3"

if ! (printf "%s\n" "$cluster" | grep -Eq '^[a-z0-9]+$')
then
    printf "Error in the cluster name.\n"
    exit 1
fi

fsid=$(uuidgen)
hostname=$(hostname)
ipaddress=$(facter ipaddress)

# Pre-cleaning.
rm -f "/tmp/$cluster.mon.keyring"
rm -fr "/var/lib/ceph/mon/$cluster-$mon_id"

Ceph_ready
Ceph_install

cat > "/etc/ceph/$cluster.conf" <<EOF
[global]
    fsid = $fsid
    #mon initial members = monid1, monid2
    #mon host = ipaddress1, ipaddress2
    #public network = <CIDR address>
    auth cluster required = cephx
    auth service required = cephx
    auth client required = cephx
    osd journal size = 1024
    filestore xattr use omap = true
    osd pool default size = 2
    osd pool default min size = 1
    osd pool default pg num = 333
    osd pool default pgp num = 333
    osd crush chooseleaf type = 1

[mon.$mon_id]
    host     = $hostname
    mon addr = $ipaddress

EOF

other_mons_host=""
other_mons_address=""
for i in $other_mons
do
    other_mon_name=$(printf "$i\n" | cut -d":" -f1)
    other_mon_id=$(printf "$i\n" | cut -d":" -f2)
    other_mon_address=$(printf "$i\n" | cut -d":" -f3)
    cat >> "/etc/ceph/$cluster.conf" <<EOF
[mon.$other_mon_id]
    host     = $other_mon_name
    mon addr = $other_mon_address

EOF
done

# Create a keyring for the monitors of the cluster.
ceph-authtool --create-keyring "/tmp/$cluster.mon.keyring" \
              --gen-key -n mon. --cap mon 'allow *'

# Generate an administrator keyring: generate a client.admin user
# and add the user to the keyring.
ceph-authtool --create-keyring "/etc/ceph/$cluster.client.admin.keyring" \
              --gen-key -n client.admin --set-uid=0                      \
              --cap mon 'allow *' --cap osd 'allow *' --cap mds 'allow'

# Add the secret key of the client.admin user in the keyring
# file of the monitor.
ceph-authtool "/tmp/$cluster.mon.keyring" \
    --import-keyring "/etc/ceph/$cluster.client.admin.keyring"
#printf "\n" >> "/tmp/$cluster.mon.keyring"
#cat "/etc/ceph/$cluster.client.admin.keyring" >> "/tmp/$cluster.mon.keyring"
#printf "\n" >> "/tmp/$cluster.mon.keyring"

# Generate a monitor map using the hostname, host IP
# address and the FSID. Save it as /tmp/monmap:
monmaptool --create --add "$mon_id" "$ipaddress" --fsid "$fsid" "/tmp/monmap"

# Create the data directory on the monitor host.
# Seems to be useless because the directory is
# automatically created with the following command.
#
#   mkdir "/var/lib/ceph/mon/$cluster-$hostname"

# Populate the monitor daemon directory. Three pieces of
# information must be provided. [1] the cluster fsid (in
# the $cluster.conf file) [2] the list of monitors (in the
# $cluster.conf file) [3] the monitor secret key and the
# secret key of client.admin user (in the keyring file).
# The secret key of client.admin user is a shared key
# which must be present in client side
# (in /etc/ceph/$cluster.client.admin.keyring) and in
# server side (in /var/lib/mon/$cluster-$hostname/).

#ceph-mon --mkfs -i "$hostname" --conf "/etc/ceph/$cluster.conf" \
#         --keyring "/tmp/$cluster.mon.keyring"                  \
#         --cluster "$cluster"

ceph-mon --mkfs -i "$mon_id" --conf "/etc/ceph/$cluster.conf"         \
         --monmap "/tmp/monmap" --keyring "/tmp/$cluster.mon.keyring" \
         --cluster "$cluster"



# To allow the stating of ceph-mon at each reboot.
touch "/var/lib/ceph/mon/$cluster-$mon_id/done"
touch "/var/lib/ceph/mon/$cluster-$mon_id/upstart"

# Restart of the daemon.
stop ceph-all
start ceph-all

# Post-cleaning.
rm -f "/tmp/$cluster.mon.keyring"
rm -f "/tmp/monmap"

# You can check the installation with:
#
#  ceph osd lspools --cluster "$cluster"
#  ceph status --cluster "$cluster"


