#!/bin/sh

# Create the "ceph" account if it does not exist.
if ! getent passwd ceph >/dev/null
then
    adduser --disabled-password --gecos "" ceph
    echo "ceph:ceph" | chpasswd
fi

# "ceph" will be sudoer.
echo "ceph ALL = (root) NOPASSWD:ALL" > "/etc/sudoers.d/ceph"
sudo chmod 0440 "/etc/sudoers.d/ceph"


