#!/bin/sh

Ceph_ready
Ceph_install

mon="$1"
cluster="$2"
fs="$3"
device="$4"

if [ "$mon" != "my self" ]
then
    scp "root@$mon:/etc/ceph/$cluster.conf" "/etc/ceph/"
    scp "root@$mon:/var/lib/ceph/bootstrap-osd/$cluster.keyring" \
        "/var/lib/ceph/bootstrap-osd/"
    chmod 600 "/var/lib/ceph/bootstrap-osd/$cluster.keyring"
fi

cluster_uuid=$(sed -rn "s/fsid[[:space:]]*=(.*)$/\1/p" "/etc/ceph/$cluster.conf" | tr -d ' ')

ceph-disk prepare --cluster "$cluster" --cluster-uuid "$cluster_uuid" \
                  --fs-type "$fs" "$device"

ceph-disk activate "$device"


