#!/bin/sh

Ceph_ready
Ceph_install

mon="$1"
cluster="$2"
id="$3"

hostname=$(hostname)

Ceph_pick_conf "$mon" "$cluster"

# Create a keyring file for the mon daemon with the secret key
# provided in the arguments of this script.
#ceph-authtool --create-keyring "/tmp/$cluster.mon.keyring" \
#              --add-key "$secret_key" -n mon. --cap mon 'allow *'


# Get the mon keyring by a request to the iniatial mon.
ceph auth get mon. -o "/tmp/$cluster.mon.keyring" -m "$mon"

# Cet the mon map by a request to the initial mon too.
ceph mon getmap -o "/tmp/monmap" -m "$mon"


# Add the secret key of the client.admin user in the keyring
# file of the monitor.
#printf "\n" >> "/tmp/$cluster.mon.keyring"
#cat "/etc/ceph/$cluster.client.admin.keyring" >> "/tmp/$cluster.mon.keyring"
#printf "\n" >> "/tmp/$cluster.mon.keyring"

# Create the data directory on the monitor host.
# Seems to be useless.
#
#   mkdir "/var/lib/ceph/mon/$cluster-$hostname"

# Populate the monitor daemon directory.
ceph-mon --mkfs -i "$id" --conf "/etc/ceph/$cluster.conf"             \
         --monmap "/tmp/monmap" --keyring "/tmp/$cluster.mon.keyring" \
         --cluster "$cluster"

# To allow the stating of ceph-mon at each reboot.
touch "/var/lib/ceph/mon/$cluster-$id/done"
touch "/var/lib/ceph/mon/$cluster-$id/upstart"

# Restart of the daemon.
stop ceph-all
start ceph-all

# Post-cleaning.
rm -f "/tmp/$cluster.mon.keyring"
rm -f "/tmp/monmap"

# You can check the installation with:
#
#  ceph osd lspools --cluster "$cluster"
#  ceph status --cluster "$cluster"


