#!/bin/sh

Ceph_ready
Ceph_install

mon="$1"
cluster="$2"
fs="$3"
device="$4"

if [ "$mon" != "my self" ]
then
    scp "root@$mon:/etc/ceph/$cluster.conf" "/etc/ceph/"
    scp "root@$mon:/var/lib/ceph/bootstrap-osd/$cluster.keyring" \
        "/var/lib/ceph/bootstrap-osd/"
    chmod 600 "/var/lib/ceph/bootstrap-osd/$cluster.keyring"
fi

cluster_uuid=$(sed -rn "s/fsid[[:space:]]*=(.*)$/\1/p" "/etc/ceph/$cluster.conf" | tr -d ' ')

ceph-disk prepare --cluster "$cluster" --cluster-uuid "$cluster_uuid" \
                  --fs-type "$fs" "$device"

# Get the id of the osd.
result=$(ceph-disk activate "$device" 2>&1)
printf "$result\n"
id=$(printf "$result\n" | grep '^added key for osd\.' | cut -d'.' -f2)

# Define UUID variable.
eval $(blkid | awk '$0 ~ "^'"$device"'" { print $2}')

printf "\n\n" >> "/etc/fstab"
printf "UUID=$UUID /var/lib/ceph/osd/$cluser-$id/ $fs defaults,noatime 0 2\n" >> "/etc/fstab"


# To check the result:
#
#   ceph osd tree --cluster "$cluster"
#   ceph status --cluster "$cluster
#


