#!/bin/sh


# Characters just in [a-z0-9] for the cluster name.
cluster="$1"
other_mons="$2" # ex: "ceph-node2:172.31.9.2 ceph-node3:172.31.9.3"

if ! (printf "%s\n" "$cluster" | grep -Eq '^[a-z0-9]+$')
then
    printf "Error in the cluster name.\n"
    exit 1
fi

fsid=$(uuidgen)
hostname=$(hostname)
ipaddress=$(facter ipaddress)

# Pre-cleaning.
rm -f "/tmp/$cluster.mon.keyring"
rm -fr "/var/lib/ceph/mon/$cluster-$hostname"

Ceph_ready
Ceph_install

other_mons_host=""
other_mons_address=""
for i in $other_mons
do
    other_mons_host="$other_mons_host, "$(printf "$i\n" | cut -d":" -f1)
    other_mons_address="$other_mons_address, "$(printf "$i\n" | cut -d":" -f2)
done

cat > "/etc/ceph/$cluster.conf" <<EOF
[global]
fsid = $fsid
mon initial members = ${hostname}${other_mons_host}
mon host = ${ipaddress}${other_mons_address}
#public network = <CIDR address>
auth cluster required = cephx
auth service required = cephx
auth client required = cephx
osd journal size = 1024
filestore xattr use omap = true
osd pool default size = 2
osd pool default min size = 1
osd pool default pg num = 333
osd pool default pgp num = 333
osd crush chooseleaf type = 1

EOF

# Create a keyring for your cluster and generate a monitor secret key.
ceph-authtool --create-keyring "/tmp/$cluster.mon.keyring" \
              --gen-key -n mon. --cap mon 'allow *'

# Generate an administrator keyring: generate a client.admin user
# and add the user to the keyring.
ceph-authtool --create-keyring "/etc/ceph/$cluster.client.admin.keyring" \
              --gen-key -n client.admin --set-uid=0                      \
              --cap mon 'allow *' --cap osd 'allow *' --cap mds 'allow'

# Add the secret key of the client.admin user in the keyring
# file of the monitor.
printf "\n" >> "/tmp/$cluster.mon.keyring"
cat "/etc/ceph/$cluster.client.admin.keyring" >> "/tmp/$cluster.mon.keyring"
printf "\n" >> "/tmp/$cluster.mon.keyring"

# Create the data directory on the monitor host.
# Seems to be useless.
#
#   mkdir "/var/lib/ceph/mon/$cluster-$hostname"

# Populate the monitor daemon directory. Three pieces of
# information must be provided. [1] the cluster fsid (in
# the $cluster.conf file) [2] the list of monitors (in the
# $cluster.conf file) [3] the monitor secret key and the
# secret key of client.admin user (in the keyring file).
# The secret key of client.admin user is a shared key
# which must be present in client side
# (in /etc/ceph/$cluster.client.admin.keyring) and in
# server side (in /var/lib/mon/$cluster-$hostname/).
ceph-mon --mkfs -i "$hostname" --conf "/etc/ceph/$cluster.conf" \
         --keyring "/tmp/$cluster.mon.keyring"                  \
         --cluster "$cluster"

# To allow the stating of ceph-mon at each reboot.
touch "/var/lib/ceph/mon/$cluster-$hostname/done"
touch "/var/lib/ceph/mon/$cluster-$hostname/upstart"

# Restart of the daemon.
stop ceph-all
start ceph-all

# Post-cleaning.
rm -f "/tmp/$cluster.mon.keyring"

# You can check the installation with:
#
#  ceph osd lspools --cluster "$cluster"
#  ceph status --cluster "$cluster"


