#!/bin/sh

# Add the release key.
URL='https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc'
wget -q -O- "$URL" | apt-key add -

# Add the Ceph repository.
CEPH_RELEASE="firefly"
echo "deb http://ceph.com/debian-$CEPH_RELEASE/ $(lsb_release -sc) main" > "/etc/apt/sources.list.d/ceph.list"

# Configure /etc/hosts. The hostname must be
# resolved with a non loopback IP address.
host_name=$(hostname)
fqdn=$(hostname -f)
ipaddress=$(facter ipaddress)
sed -r -i "s/^.*$fqdn.*$/$ipaddress\t$fqdn\t$host_name/" "/etc/hosts"


