#!/bin/sh

Ceph_ready
Ceph_install

mon="$1"
cluster="$2"
secret_key="$3"

hostname=$(hostname)

# Pre-cleaning.
rm -f "/tmp/$cluster.mon.keyring"

if [ "$mon" != "my self" ]
then
    scp "root@$mon:/etc/ceph/$cluster.conf" "/etc/ceph/"
    scp "root@$mon:/etc/ceph/$cluster.client.admin.keyring" "/etc/ceph"
fi

# Create a keyring file for the mon daemon with the secret key
# provided in the arguments of this script.
ceph-authtool --create-keyring "/tmp/$cluster.mon.keyring" \
              --add-key "$secret_key" -n mon. --cap mon 'allow *'

# Create the data directory on the monitor host.
# Seems to be useless.
#
#   mkdir "/var/lib/ceph/mon/$cluster-$hostname"

# Populate the monitor daemon directory.
ceph-mon --mkfs -i "$hostname" --conf "/etc/ceph/$cluster.conf" \
         --keyring "/tmp/$cluster.mon.keyring"                  \
         --cluster "$cluster"

# To allow the stating of ceph-mon at each reboot.
touch "/var/lib/ceph/mon/$cluster-$hostname/done"
touch "/var/lib/ceph/mon/$cluster-$hostname/upstart"

# Restart of the daemon.
stop ceph-all
start ceph-all

# Post-cleaning.
rm -f "/tmp/$cluster.mon.keyring"

# You can check the installation with:
#
#  ceph osd lspools --cluster "$cluster"
#  ceph status --cluster "$cluster"


